import { Search, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import type { Order } from "../../../shared/domain/types";
import { formatVnd } from "../../../shared/utils";

interface OrderManagementProps { orders: Order[]; onStatusChange: (id: string, status: Order["status"]) => void; }

export function OrderManagement({ orders, onStatusChange }: OrderManagementProps) {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("ALL");
  const filtered = useMemo(() => orders.filter((o) => (status === "ALL" || o.status === status) && `${o.id} ${o.pickup} ${o.dropoff}`.toLowerCase().includes(query.toLowerCase())), [orders, query, status]);

  return <div className="rounded-[2rem] border border-slate-200 bg-white p-5 md:p-6"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><h3 className="text-lg font-medium text-[#14284b]">Order management</h3><div className="flex flex-col gap-2 sm:flex-row"><label className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2"><Search className="h-4 w-4 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search order..." className="w-full outline-none text-sm" /></label><label className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2"><SlidersHorizontal className="h-4 w-4 text-slate-400" /><select value={status} onChange={(e) => setStatus(e.target.value)} className="bg-transparent text-sm outline-none"><option value="ALL">All statuses</option>{["PENDING","MATCHING","ASSIGNED","PICKING_UP","IN_TRANSIT","DELIVERED","COMPLETED","CANCELLED"].map((s) => <option key={s}>{s}</option>)}</select></label></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b border-slate-100 text-xs uppercase tracking-wider text-slate-400"><th className="pb-3">Order</th><th className="pb-3">Route</th><th className="pb-3">Fee</th><th className="pb-3">Status</th><th className="pb-3">Action</th></tr></thead><tbody>{filtered.map((order) => <tr key={order.id} className="border-b border-slate-50"><td className="py-4 font-medium text-[#14284b]">{order.id}</td><td className="py-4 text-slate-500">{order.pickup} → {order.dropoff}</td><td className="py-4 text-slate-600">{formatVnd(order.fee)}</td><td className="py-4"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-600">{order.status}</span></td><td className="py-4"><select value={order.status} onChange={(e) => onStatusChange(order.id, e.target.value as Order["status"])} className="rounded-lg border border-slate-200 px-2 py-1 text-xs"><option value="PENDING">PENDING</option><option value="MATCHING">MATCHING</option><option value="ASSIGNED">ASSIGNED</option><option value="PICKING_UP">PICKING_UP</option><option value="IN_TRANSIT">IN_TRANSIT</option><option value="DELIVERED">DELIVERED</option><option value="COMPLETED">COMPLETED</option><option value="CANCELLED">CANCELLED</option></select></td></tr>)}</tbody></table>{filtered.length === 0 && <p className="py-8 text-center text-sm text-slate-400">No matching orders.</p>}</div></div>;
}
