import { useState, type FormEvent } from "react";
import { ArrowLeft, Send, UserRound } from "lucide-react";
import type { Language } from "../../../shared/i18n";
export function Chat({ lang, onBack }: { lang: Language; onBack: () => void }) {
  const vi = lang === "vi";
  const [draft, setDraft] = useState("");
  const [messages, setMessages] = useState([{ from: "customer", text: vi ? "Chào bạn, bạn đến lấy hàng khoảng mấy giờ?" : "Hi, around what time will you arrive for pickup?", time: "09:41" }, { from: "shipper", text: vi ? "Mình sẽ đến trong khoảng 5 phút nữa." : "I'll be there in about 5 minutes.", time: "09:42" }]);
  function send(e: FormEvent) { e.preventDefault(); if (!draft.trim()) return; setMessages(m => [...m, { from: "shipper", text: draft.trim(), time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) }]); setDraft(""); }
  return <section className="mx-auto w-full max-w-3xl px-4 py-6 sm:py-10"><button onClick={onBack} className="mb-4 inline-flex items-center gap-2 text-sm font-semibold text-[#14284b]"><ArrowLeft className="h-4 w-4"/>{vi ? "Quay lại đơn giao" : "Back to delivery"}</button><div className="overflow-hidden rounded-[1.75rem] border border-slate-200 bg-white shadow-sm"><header className="flex items-center gap-3 border-b border-slate-100 p-4 sm:p-5"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-slate-100 text-[#14284b]"><UserRound/></div><div className="flex-1"><h1 className="font-semibold text-[#14284b]">{vi ? "Trò chuyện với khách hàng" : "Chat with customer"}</h1><p className="text-xs text-slate-500">SOMI-240126 · {vi ? "Khách hàng" : "Customer"}</p></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs text-amber-700">{vi ? "Mô phỏng" : "Demo"}</span></header><div className="flex min-h-72 flex-col gap-3 bg-slate-50 p-4 sm:p-6">{messages.map((m, i) => <div key={`${m.time}-${i}`} className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm ${m.from === "shipper" ? "ml-auto bg-[#14284b] text-white" : "mr-auto border border-slate-200 bg-white text-slate-700"}`}><p>{m.text}</p><p className={`mt-1 text-right text-[10px] ${m.from === "shipper" ? "text-white/60" : "text-slate-400"}`}>{m.time}</p></div>)}</div><form onSubmit={send} className="flex gap-2 border-t border-slate-100 p-3 sm:p-4"><input value={draft} onChange={e => setDraft(e.target.value)} placeholder={vi ? "Nhập tin nhắn..." : "Type a message..."} className="min-w-0 flex-1 rounded-full border border-slate-200 px-4 py-3 text-sm outline-none focus:border-[#14284b]"/><button aria-label={vi ? "Gửi tin nhắn" : "Send message"} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-[#14284b] text-white"><Send className="h-4 w-4"/></button></form></div><p className="mt-3 text-xs text-slate-500">{vi ? "Tin nhắn đang được lưu trong trạng thái giao diện; cần backend để chat theo thời gian thực." : "Messages are local to this UI demo; a backend is needed for real-time chat."}</p></section>;
}
