import { useState, type ReactNode } from "react";
import { ArrowUpRight, Clock3, PackageCheck, WalletCards } from "lucide-react";
import type { Language } from "../../../shared/i18n";
import { useShipperCopy } from "../i18n";
type Period = "day" | "week" | "month";
const data: Record<Period, { income: string; orders: string; hours: string; average: string; bars: number[] }> = {
  day: { income: "₫420,000", orders: "12", hours: "4.8h", average: "₫35,000", bars: [45, 65, 35, 82, 55, 70, 48] },
  week: { income: "₫2,180,000", orders: "68", hours: "28.5h", average: "₫32,059", bars: [55, 72, 46, 84, 62, 76, 38] },
  month: { income: "₫7,420,000", orders: "245", hours: "112h", average: "₫30,286", bars: [66, 52, 78, 60, 88, 72, 95] },
};
export function Earnings({ lang, onWithdraw }: { lang: Language; onWithdraw: () => void }) {
  const c = useShipperCopy(lang).earnings; const [period, setPeriod] = useState<Period>("day"); const d = data[period]; const labels = lang === "vi" ? { day: "Ngày", week: "Tuần", month: "Tháng", today: "Thu nhập hôm nay", withdraw: "Rút tiền", available: "Số dư khả dụng", completed: "Đơn hoàn tất", hours: "Giờ hoạt động", average: "Trung bình / đơn", breakdown: "Thống kê thu nhập", history: "Lịch sử thu nhập" } : { day: "Day", week: "Week", month: "Month", today: "Today's earnings", withdraw: "Withdraw", available: "Available balance", completed: "Completed deliveries", hours: "Active hours", average: "Average / delivery", breakdown: "Earnings statistics", history: "Earnings history" };
  return <section className="mx-auto w-full max-w-6xl px-4 py-6 sm:px-5 sm:py-8 md:px-8 md:py-12"><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><h1 className="text-2xl font-semibold tracking-[-0.04em] text-[#14284b] sm:text-3xl">{c.title}</h1><button onClick={onWithdraw} className="rounded-full bg-[#14284b] px-5 py-3 text-sm font-semibold text-white">{labels.withdraw}</button></div><div className="mb-4 flex w-fit gap-1 rounded-full bg-slate-100 p-1">{(["day", "week", "month"] as Period[]).map(p => <button key={p} onClick={() => setPeriod(p)} className={`rounded-full px-5 py-2 text-sm font-semibold ${period === p ? "bg-[#14284b] text-white" : "text-slate-600 hover:bg-white"}`}>{labels[p]}</button>)}</div><div className="mb-4 rounded-[1.5rem] bg-[#14284b] p-5 text-white sm:p-6"><p className="text-sm text-white/70">{labels.available}</p><p className="mt-2 text-3xl font-semibold">₫1,250,000</p><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-white/70">{labels.today}</p><p className="text-lg font-semibold">{d.income}</p></div><button onClick={onWithdraw} className="rounded-full bg-white px-4 py-2 text-sm font-semibold text-[#14284b]">{labels.withdraw}</button></div></div><div className="grid gap-4 sm:grid-cols-3"><Card icon={<PackageCheck/>} label={labels.completed} value={d.orders}/><Card icon={<Clock3/>} label={labels.hours} value={d.hours}/><Card icon={<ArrowUpRight/>} label={labels.average} value={d.average}/></div><div className="mt-5 rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold text-[#14284b]">{labels.breakdown}</h2><p className="mt-1 text-sm text-slate-500">{d.income}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">+12.4%</span></div><div className="mt-8 flex h-44 items-end gap-2 sm:gap-4">{d.bars.map((height,index)=><div key={index} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t-xl bg-[#14284b]" style={{height:`${height}%`}}/><span className="text-[10px] text-slate-400">{lang === "vi" ? ["T2","T3","T4","T5","T6","T7","CN"][index] : ["M","T","W","T","F","S","S"][index]}</span></div>)}</div></div><div className="mt-5 rounded-[2rem] border border-slate-200 bg-white p-5 sm:p-7"><h2 className="font-semibold text-[#14284b]">{labels.history}</h2>{[["SOMI-240125","+₫28,000"],["SOMI-240119","+₫33,600"],["SOMI-240112","+₫31,200"]].map(row=><div key={row[0]} className="flex justify-between gap-4 border-b border-slate-100 py-4 text-sm"><span className="text-slate-600">{row[0]}</span><b className="text-emerald-700">{row[1]}</b></div>)}</div></section>;
}
function Card({icon,label,value}:{icon:ReactNode;label:string;value:string}){return <div className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-50 text-[#14284b]">{icon}</div><p className="mt-5 text-xs text-slate-400">{label}</p><p className="mt-1 text-xl font-semibold text-[#14284b]">{value}</p></div>}
