import { ArrowLeft, Box, Clock3, MapPin, UserRound, Weight } from "lucide-react";
import type { ReactNode } from "react";
import type { DeliveryOfferData } from "../../../shared/domain/types";
import { formatVnd } from "../../../shared/utils";
import { useShipperCopy } from "../i18n";
import type { Language } from "../../../shared/i18n";
interface Props { lang: Language; offer?: DeliveryOfferData; onBack: () => void; onAccept: (id: string) => void; onReject: (id: string) => void; }
export function OfferDetail({ lang, offer, onBack, onAccept, onReject }: Props) {
  const c = useShipperCopy(lang).detail;
  if (!offer) return <section className="mx-auto max-w-6xl px-4 py-8 sm:px-6 md:py-12"><button onClick={onBack} className="flex items-center gap-2 text-sm font-semibold text-[#14284b]"><ArrowLeft className="h-4 w-4" />{c.back}</button><div className="mt-8 rounded-[2rem] bg-white p-10 text-center text-slate-500">{c.notFound}</div></section>;
  return <section className="mx-auto w-full max-w-5xl px-4 py-6 sm:px-5 sm:py-8 md:px-8 md:py-12"><button onClick={onBack} className="flex items-center gap-2 text-sm font-semibold text-[#14284b]"><ArrowLeft className="h-4 w-4" />{c.back}</button><div className="mt-5 grid gap-5 lg:grid-cols-[1fr_340px]"><div className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">{offer.order.service === "EXPRESS" ? c.express : c.standard}</span><h1 className="mt-3 text-2xl font-semibold tracking-[-0.03em] text-[#14284b]">{c.title}</h1><p className="mt-1 text-sm text-slate-500">{offer.order.id}</p></div><div className="text-right"><p className="text-xs text-slate-400">{c.estimatedEarnings}</p><p className="text-2xl font-semibold text-[#14284b]">{formatVnd(offer.order.fee * .8)}</p></div></div><div className="mt-8 space-y-5"><Location label={c.pickup} value={offer.order.pickup} /><div className="ml-3 h-7 border-l border-dashed border-slate-300" /><Location label={c.dropoff} value={offer.order.dropoff} /></div><div className="mt-8 grid gap-3 sm:grid-cols-3"><Info icon={<Box />} label={c.package} value={offer.order.service === "EXPRESS" ? c.express : c.standard} /><Info icon={<Weight />} label={c.weight} value={`${offer.order.weightKg} kg`} /><Info icon={<Clock3 />} label={c.eta} value={`${offer.etaMinutes} min`} /></div></div><aside className="h-fit rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-slate-100"><UserRound className="h-5 w-5 text-[#14284b]" /></div><div><p className="text-xs text-slate-400">{c.customer}</p><p className="text-sm font-semibold text-[#14284b]">{offer.order.customer || "SOMI Customer"}</p></div></div><div className="mt-6 border-t border-slate-100 pt-5"><p className="text-xs text-slate-400">{c.estimatedEarnings}</p><p className="mt-1 text-2xl font-semibold text-[#14284b]">{formatVnd(offer.order.fee * .8)}</p></div><div className="mt-5 grid gap-3"><button onClick={() => onAccept(offer.order.id)} className="rounded-full bg-[#14284b] px-4 py-3 text-sm font-semibold text-white hover:bg-[#1d3968]">{c.accept}</button><button onClick={() => onReject(offer.order.id)} className="rounded-full border border-slate-200 px-4 py-3 text-sm font-semibold text-slate-600 hover:bg-slate-50">{c.reject}</button></div></aside></div></section>;
}
function Location({ label, value }: { label: string; value: string }) { return <div className="flex gap-3"><MapPin className="mt-0.5 h-5 w-5 shrink-0 text-[#14284b]" /><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold text-[#14284b]">{value}</p></div></div>; }
function Info({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <div className="rounded-2xl bg-slate-50 p-4"><div className="flex items-center gap-2 text-slate-400">{icon}<span className="text-xs">{label}</span></div><p className="mt-2 text-sm font-semibold text-[#14284b]">{value}</p></div>; }
